theme: jekyll-theme-minimal
title: Antonio Sze-To
description: Antonio is an expert in Data Science, Machine Learning, Deep Learning specialized in Python, Tensorflow or Keras. Contact him <a href="http://www.google.com">here</a> for project opportunities.
logo: head.png
