theme: jekyll-theme-minimal
title: Antonio Sze-To, Ph.D.
description: Antonio is experienced in Machine Learning Software Development, specialized in AI/Deep Learning, Python and Tensorflow/Keras. Contact him <a href="mailto:antonioszeto@gmail.com">here</a>.
logo: head.png
