theme: jekyll-theme-minimal
title: Antonio Sze-To, Ph.D.
description: Antonio is an expert in Data Science, Machine Learning and Deep Learning specialized in Python, Tensorflow and Keras. Contact him <a href="mailto:antonioszeto@gmail.com">here</a> for project opportunities.
logo: head.png
